name: Test
run-name: Test end-to-end
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
# # note: due to the low volume of pushes, it's currently preferred to not cancel previous runs
# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
#   cancel-in-progress: true
defaults:
  run:
    shell: bash
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
      - run: npm install
      - run: npm run build
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        browser:
          - electron
          - chrome
          - firefox
          - webkit
          - chromium
        exclude:
          - os: macos-latest
            browser: chromium
        include:
          - os: ubuntu-latest
            name: Linux
          - os: macos-latest
            name: macOS

    name: ${{ matrix.name }} - ${{ matrix.browser }}
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    steps:

      - name: Setup firefox (macOS)
        if: matrix.os == 'macos-latest' && matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@v1

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: leanprover/lean-action@v1
        with:
          lake-package-directory: "demo/server/LeanProject"
          use-github-cache: false
          use-mathlib-cache: false
          auto-config: false
          build: false
          test: false
          lint: false

      - uses: actions/setup-node@v4

      - run: npm install
      
      - name: Run tests
        run: npm run test

      - name: Run tests (Windows User Agent)
        if: matrix.browser == 'chromium'
        run: npm run test:windows
